return {
	{
		"__XXX",
		"__X.X",
		"__X XXXX",
		"XXX* *.X",
		"X. *@XXX",
		"XXXX*X",
		"___X.X",
		"___XXX"
	},
	{
		"____XXXXX_____________",
		"____X   X_____________",
		"____X*  X_____________",
		"__XXX  *XXX___________",
		"__X  *  * X___________",
		"XXX X XXX X_____XXXXXX",
		"X   X XXX XXXXXXX  ..X",
		"X *  *             ..X",
		"XXXXX XXXX X@XXXX  ..X",
		"____X      XXX__XXXXXX",
		"____XXXXXXXX__________"
	},
	{
		"XXXXXXXXXXXX",
		"X..  X     XXX",
		"X..  X *  *  X",
		"X..  X*XXXX  X",
		"X..    @ XX  X",
		"X..  X X  * XX",
		"XXXXXX XX* * X",
		"__X *  * * * X",
		"__X    X     X",
		"__XXXXXXXXXXXX"
	},
	{
		"________XXXXXXXX",
		"________X     @X",
		"________X *X* XX",
		"________X *  *X",
		"________XX* * X",
		"XXXXXXXXX * X XXX",
		"X....  XX *  *  X",
		"XX...    *  *   X",
		"X....  XXXXXXXXXX",
		"XXXXXXXX"
	},
	{
		"______________XXXXXXXX",
		"______________X  ....X",
		"___XXXXXXXXXXXX  ....X",
		"___X    X  * *   ....X",
		"___X ***X*  * X  ....X",
		"___X  *     * X  ....X",
		"___X ** X* * *XXXXXXXX",
		"XXXX  * X     X",
		"X   X XXXXXXXXX",
		"X    *  XX",
		"X **X** @X",
		"X   X   XX",
		"XXXXXXXXX"
	},
	{
		"________XXXXX",
		"________X   XXXXX",
		"________X X*XX  X",
		"________X     * X",
		"XXXXXXXXX XXX   X",
		"X....  XX *  *XXX",
		"X....    * ** XX",
		"X....  XX*  * @X",
		"XXXXXXXXX  *  XX",
		"________X * *  X",
		"________XXX XX X",
		"__________X    X",
		"__________XXXXXX"
	},
	{
		"XXXXXX__XXX",
		"X..  X_XX@XX",
		"X..  XXX   X",
		"X..     ** X",
		"X..  X X * X",
		"X..XXX X * X",
		"XXXX * X*  X",
		"___X  *X * X",
		"___X *  *  X",
		"___X  XX   X",
		"___XXXXXXXXX"
	},
	{
		"_______XXXXX",
		"_XXXXXXX   XX",
		"XX X @XX ** X",
		"X    *      X",
		"X  *  XXX   X",
		"XXX XXXXX*XXX",
		"X *  XXX ..X",
		"X * * * ...X",
		"X    XXX...X",
		"X ** X_X...X",
		"X  XXX_XXXXX",
		"XXXX"
	},
	{
		"__XXXX",
		"__X  XXXXXXXXXXX",
		"__X    *   * * X",
		"__X *X * X  *  X",
		"__X  * *  X    X",
		"XXX *X X  XXXX X",
		"X@X* * *  XX   X",
		"X    * X*X   X X",
		"XX  *    * * * X",
		"_XXXX  XXXXXXXXX",
		"__XXX  XXX",
		"__X      X",
		"__X      X",
		"__X......X",
		"__X......X",
		"__X......X",
		"__XXXXXXXX"
	},
	{
		"__________XXXXXXX",
		"__________X  ...X",
		"______XXXXX  ...X",
		"______X      ...X",
		"______X  XX  ...X",
		"______XX XX  ...X",
		"_____XXX XXXXXXXX",
		"_____X *** XX",
		"_XXXXX  * * XXXXX",
		"XX   X* *   X   X",
		"X@ *  *    *  * X",
		"XXXXXX ** * XXXXX",
		"_____X *    X",
		"_____XXXX XXX",
		"________X  X",
		"________X  X",
		"________X  X",
		"________XXXX"
	},
	{
		"______________XXXX",
		"_________XXXXXX  X",
		"_________X       X",
		"_________X  XXXX XXX",
		"_XXX__XXXXX XXX    X",
		"XX@XXXX   *** X    X",
		"X **   ** *   X....XX",
		"X  ***X    *  X.....X",
		"X *   X ** ** X.....X",
		"XXX   X  *    X.....X",
		"__X   X * * * X.....X",
		"__X XXXXXXX XXX.....X",
		"__X   X  * *  X.....X",
		"__XXX X ** * *XXXXXXX",
		"____X X  *      X",
		"____X X *** *** X",
		"____X X       X X",
		"____X XXXXXXXXX X",
		"____X           X",
		"____XXXXXXXXXXXXX"
	},
	{
		"__________XXXX",
		"_____XXXX_X  X",
		"___XXX  XXX* X",
		"__XX   @  *  X",
		"_XX  * **XX XX",
		"_X  X*XX     X",
		"_X X * ** X XXX",
		"_X   * X  X * XXXXX",
		"XXXX    X  ** X   X",
		"XXXX XX *         X",
		"X.    XXX  XXXXXXXX",
		"X.. ..X_XXXX",
		"X...X.X",
		"X.....X",
		"XXXXXXX"
	},
	{
		"__XXXXXXXXX",
		"__X&.&X&.&X",
		"__X.&.&.&.X",
		"__X&.&.&.&X",
		"__X.&.&.&.X",
		"__X&.&.&.&X",
		"__XXX   XXX",
		"____X   X",
		"XXXXXX XXXXXX",
		"X           X",
		"X * * * * * X",
		"XX * * * * XX",
		"_X* * * * *X",
		"_X   *@*   X",
		"_X  XXXXX  X",
		"_XXXX___XXXX"
	},
	{
		"____XXXXXXXXX",
		"__XXX   XX  XXXXX",
		"XXX      X  X   XXXX",
		"X  ** X* X  X  ... X",
		"X X  *X@*XX X X.X. X",
		"X  XX X*  X    ... X",
		"X *X    * X X X.X. X",
		"X    XX  XX* * ... X",
		"X * XX   X  X*X.X. X",
		"XX **  *   *  *... X",
		"_X*  XXXXXX    XX  X",
		"_X   X____XXXXXXXXXX",
		"_XXXXX"
	},
	{
		"XXXXXXXXXXXXXXXX",
		"X              X",
		"X X XXXXXX     X",
		"X X  * * * *X  X",
		"X X   *@*   XX XX",
		"X X X* * *XXX...X",
		"X X   * *  XX...X",
		"X XXX*** * XX...X",
		"X     X XX XX...X",
		"XXXXX   XX XX...X",
		"____XXXXX     XXX",
		"________X     X",
		"________XXXXXXX"
	},
	{
		"_______XXXX",
		"____XXXX  X",
		"___XX  X  X",
		"___X  * * X",
		"_XXX X*   XXXX",
		"_X  *  XX*   X",
		"_X  X @ * X *X",
		"_X  X      * XXXX",
		"_XX XXXX*XX     X",
		"_X *X.....X X   X",
		"_X  *...&. *X XXX",
		"XX  X.....X   X",
		"X   XXX XXXXXXX",
		"X **  X  X",
		"X  X     X",
		"XXXXXX   X",
		"_____XXXXX"
	},
	{
		"XXXXX",
		"X   XX",
		"X    X__XXXX",
		"X *  XXXX  X",
		"X  ** *   *X",
		"XXX@ X*    XX",
		"_X  XX  * * XX",
		"_X *  XX XX .X",
		"_X  X*XX*  X.X",
		"_XXX   *..XX.X",
		"__X    X.&...X",
		"__X ** X.....X",
		"__X  XXXXXXXXX",
		"__X  X",
		"__XXXX"
	},
	{
		"_______XXXXXXX",
		"_XXXXXXX     X",
		"_X     X *@* X",
		"_X** X   XXXXXXXXX",
		"_X XXX......XX   X",
		"_X   *......XX X X",
		"_X XXX......     X",
		"XX   XXXX XXX X*XX",
		"X  X*   X  *  X X",
		"X  * ***  X *XX X",
		"X   * * XXX** X X",
		"XXXXX     *   X X",
		"____XXX XXX   X X",
		"______X     X   X",
		"______XXXXXXXX  X",
		"_____________XXXX"
	},
	{
		"______XXXXXXXXXXXX",
		"______X  .  XX   X",
		"______X X.     @ X",
		"_XXXXXX XX...X XXXX",
		"XX  XX...XXXX     XXXX",
		"X * XX...    * X  *  X",
		"X     .. XX X XX XX  X",
		"XXXX*XXX*X *  X   X XX",
		"_XXX  X    XX* ** X X",
		"_X   ** X X * X *XX X",
		"_X                  X",
		"_XXXXXXXXXXXXXXXXX  X",
		"_________________XXXX"
	},
	{
		"________XXXXXX",
		"________X   @XXXX",
		"______XXXXX *   X",
		"______X   XX    XXXX",
		"______X *XX  XX    X",
		"______X   X  XXXXX X",
		"______X X** *    X X",
		"______X  * * XXX X X",
		"______X X   *  X X X",
		"______X X  X*X   X X",
		"_____XX XXXX   X X X",
		"_____X  *  XXXXX X X XXXX",
		"____XX    *     *  XXX  XXXX",
		"XXXXX  XXX * *X * X   .....X",
		"X     XX      X  XX  X.....X",
		"X ****    XXXXXX*XX   X.XX.X",
		"XX    XX              X....X",
		"_XX  XXXXXXXXXXXXXXX   ....X",
		"__X  X_____________XXXXX_ XX",
		"__XXXX_________________XXXX"
	},
	{
		"_______XXXXXXXXXXXX",
		"_______X..........X",
		"_____XXX.X.X.X.X..X",
		"_____X   .........X",
		"_____X@ * * * &.&.X",
		"____XXXXXXX XXXXXXX",
		"_XXXX   X    XX  X",
		"XX    * X    X * XX",
		"X  X*X XXX XXX*   XX",
		"X *  * *   X * * * X",
		"X  X * XX       X* X",
		"X   *XXXX*XXXX*XX  X",
		"XXXX  XX   X    X  X",
		"___X* XX   X X **  X",
		"___X   X * X  *    X",
		"___XXX X ** X  * XXX",
		"_____X X    X * XX",
		"_____X XXXXXXXX X",
		"_____X          X",
		"_____XXXXXXXXXXXX"
	},
	{
		"___XXXXXXXXXX",
		"___X..  X   X",
		"___X..      X",
		"___X..  X  XXXX",
		"__XXXXXXX  X  XX",
		"__X            X",
		"__X  X  XX  X  X",
		"XXXX XX  XXXX XX",
		"X  *  XXXXX X  X",
		"X X *  *  X *  X",
		"X @*  *   X   XX",
		"XXXX XX XXXXXXX",
		"___X    X",
		"___XXXXXX"
	},
	{
		"____________XXXX",
		"_XXXXXXXXXXXX  XXXXX",
		"_X    X  X  *  X   XX",
		"_X * * *  * X * *   X",
		"_XX* *   X @X *   * X",
		"XXX   XXXXXXXXXXXX XX",
		"X  * *X  X......X *X",
		"X X   X  X......XX X",
		"X  XX XX X .....X  X",
		"X X      *...... * X",
		"X X * XX X......X  X",
		"X  * *X  X......X *X",
		"X *   X  XX*XXXXX  X",
		"X * * XXXX * *  * *X",
		"XX X     * * * *   XXX",
		"_X  XXXXXX *    *    X",
		"_X         X XXXXXXX X",
		"_XXXXXXX X*          X",
		"_______X   XXXXXXXXXXX",
		"_______XXXXX"
	},
	{
		"_______XXXXXXX",
		"_______X  X  XXXX",
		"_______X *X* X  XX",
		"XXXXXXXX  X  X   XXXXXXXX",
		"X....  X *X* X  *X  X   X",
		"X....X X     X*  X      X",
		"X..X.    *X  X *    X*  X",
		"X... @XX  X* X*  X  X   X",
		"X.... XX *X     *XXXXXXXX",
		"XXXXXXXX  X**X*  X",
		"_______X *X  X  *X",
		"_______X  X  X   X",
		"_______XXXX  XXXXX",
		"__________XXXX"
	},
	{
		"___XXXXXXXXXX",
		"___X........XXXX",
		"___X.X.X....X  X",
		"___X........** X",
		"___X     .XXX  XXXX",
		"_XXXXXXXXX  * X   X",
		"_X     *   * *  * X",
		"_X  X    X  * *X  X",
		"_XX XXXXX   X  X  X",
		"_X *     X   XXXX X",
		"XX  *X   X XX  X  X",
		"X    XX*XXX    X  XX",
		"X *    * X  X  X   X",
		"XXXXX    X XX X XX XX",
		"____X*X X  *  * *   X",
		"____X@X  *X***  X   X",
		"____XXX  *      XXXXX",
		"______XX  X  X  X",
		"_______XXXXXXXXXX"
	},
	{
		"_______________XXXX",
		"__________XXXXXX  XXXXX",
		"____XXXXXXX       X   X",
		"____X      * * XX X X X",
		"____X  XXXX *  X     .X",
		"____X      * X X XX.X.X",
		"____XX*XXXX* * * XX.X.X",
		"____X     X    XXXX.XXX",
		"____X *   XXXXXX  X.X.X",
		"XXXXXX***XX      @X.X.X",
		"X      X    X*X*XXX. .X",
		"X XXXX X*****    X ...X",
		"X X    *     X   X ...X",
		"X X   XX XX     XXX...X",
		"X XXXXXX*XXXXXX  XXXXXX",
		"X        X____X  X",
		"XXXXXXXXXX____XXXX"
	},
	{
		"XXXXXXXXX",
		"X       X",
		"X       XXXX",
		"XX XXXX X  X",
		"XX X@XX    X",
		"X *** *  **X",
		"X  X XX *  X",
		"X  X XX  * XXXX",
		"XXXX  *** *X  X",
		"_X   XX   ....X",
		"_X X   X X.. .X",
		"_X   X X XX...X",
		"_XXXXX *  X...X",
		"_____XX   XXXXX",
		"______XXXXX"
	},
	{
		"_XXXXXXXXXXXXXXXXX",
		"_X...   X    X   XXX",
		"XX.....  *XX X X * X",
		"X......X  *  X  *  X",
		"X......X  X  X X X XX",
		"XXXXXXXXX *  * X X  XXX",
		"__X     X*XX* XX XX   X",
		"_XX   *    X *  *   X X",
		"_X  XX XXX X  XXXXX*X X",
		"_X * **     *   *     X",
		"_X *    *XX* XXXXXXXX X",
		"_XXXXXXX  @ XX______XXX",
		"_______XXXXXX"
	},
	{
		"_____XXXXXXX",
		"_____X@ X  X",
		"_____X *   X",
		"____XXX XX X",
		"_XXXX *  X XX",
		"_X       X  XX",
		"_X * *XXXX * X",
		"_X ** X  X  *X",
		"_X*  *   X*  X",
		"XX  **X   ** XX",
		"X **  X  X  * X",
		"X     XXXX *  X",
		"X  X*XX..XX   X",
		"XXX .X....XXXXX",
		"__X .......XX",
		"__X....   ..X",
		"__XXXXXXXXXXX"
	},
	{
		"________________XXXXX",
		"_______XXXXXX XXX   XXXX",
		"___XXXXX    XXX * *  * X",
		"XXXX  XX X* *    * X   X",
		"X....   ** * *  *   X*XX",
		"X.. X XX X   XXX*XX X  X",
		"X....    X XXX    X    X",
		"X....    X XX  *  XXX* X",
		"X..XXXXXX  *  X  XXXX XX",
		"XXXX____X   XXX    @  X",
		"________XXXXXXXXXXXXXXX"
	},
	{
		"_XXXXX",
		"_X   XXXXXXX",
		"_X * XXX   X",
		"_X *    ** X",
		"_XX XXXX   X",
		"XXX X  X XXX",
		"X   X  X@XX",
		"X **    * X",
		"X   X X * XXXX",
		"XXXXX X   X  X",
		"_X   *XXXX   X",
		"_X  *     *  X",
		"_XX   XXXXX XX",
		"_XXXXXXXXXX  X",
		"XX....X *  * X",
		"X.....X **X  X",
		"X.. ..X *  * X",
		"X.....*   X  X",
		"XX  XXXXXXXXXX",
		"_XXXX"
	},
	{
		"_XXXXXXX",
		"_X  X  XXXXX",
		"XX  X  X...XXX",
		"X  *X  X...  X",
		"X * X** ...  X",
		"X  *X  X... .X",
		"X   X *XXXXXXXX",
		"XX*       * * X",
		"XX  X  ** X   X",
		"_XXXXXX  XX**@X",
		"______X      XX",
		"______XXXXXXXX"
	},
	{
		"__XXXX",
		"__X  XXXXXXXXX",
		"_XX  XX @X   X",
		"_X  *X * *   XXXX",
		"_X*  *  X * *X  XX",
		"XX  *XX X* *     X",
		"X  X  X X   ***  X",
		"X *    *  *XX XXXX",
		"X * * X*X  X  X",
		"XX  XXX  XXX* X",
		"_X  X....     X",
		"_XXXX......XXXX",
		"___X....XXXX",
		"___X...XX",
		"___X...X",
		"___XXXXX"
	},
	{
		"______XXXX",
		"__XXXXX  X",
		"_XX     *X",
		"XX *  XX XXX",
		"X@* * X *  X",
		"XXXX XX   *X",
		"_X....X* * X",
		"_X....X   *X",
		"_X....  ** XX",
		"_X... X *   X",
		"_XXXXXX* *  X",
		"______X   XXX",
		"______X* XXX",
		"______X  X",
		"______XXXX"
	},
	{
		"XXXXXXXXXXXX",
		"XX     XX  X",
		"XX   *   * X",
		"XXXX XX ** X",
		"X   * X    X",
		"X *** X XXXX",
		"X   X X * XX",
		"X  X  X  * X",
		"X *X *X    X",
		"X   ..X XXXX",
		"XXXX.. * X@X",
		"X.....X *X X",
		"XX....X  * X",
		"XXX..XX    X",
		"XXXXXXXXXXXX"
	},
	{
		"XXXXXXXXXXXX__XXXXXX",
		"X   X    X@XXXX....X",
		"X   **X       .....X",
		"X   X XXX   XX ....X",
		"XX XX XXX  X   ....X",
		"_X * *     X XX XXXX",
		"_X  * *XX  X       X",
		"XXXX X  XXXX XX XX X",
		"X  X X*   XX XX    X",
		"X *  *  X XX XXXXXXX",
		"X X * *    X X",
		"X  * XX XX X X",
		"X **     **  X",
		"XX XX XXX *  X",
		"_X    X_X    X",
		"_XXXXXX_XXXXXX"
	},
	{
		"_____XXXX",
		"___XXX  XX",
		"XXXX  *  X",
		"X   * *  XXXX",
		"X *   X *   X XXXX",
		"X  X  X   * X X..X",
		"XX*X* XXXX*XXXX..X",
		"_X   XXXXX XX ...X",
		"_X*X XX@XX XX  ..X",
		"_X X    *     ...X",
		"_X   XXXX XXX  ..X",
		"_XXX XX X  XX ...X",
		"__XX* XXXX* XXX..X",
		"__X   XX    X_X..X",
		"_XX **XX  * X_XXXX",
		"_X     **** X",
		"_X * XXX    X",
		"_X   X_XXXXXX",
		"_XXXXX"
	},
	{
		"XXXXXXXXXXX",
		"X......   XXXXXXXXX",
		"X......   X  XX   X",
		"X..XXX *    *     X",
		"X... * * X  XXX   X",
		"X...X*XXXXX    X  X",
		"XXX    X   X*  X *XXX",
		"__X  ** * *  *XX  * X",
		"__X  *   X*X  XX    X",
		"__XXX XX X  * XXXXXXX",
		"___X  * * XX XX",
		"___X    *  *  X",
		"___XX   X X   X",
		"____XXXXX@XXXXX",
		"________XXX"
	},
	{
		"_XXXXXXXXX",
		"_X....   XX",
		"_X.X.X  * XX",
		"XX....X X @XX",
		"X ....X  X  XX",
		"X     X* XX* X",
		"XX XXX  *    X",
		"_X*  * * *X  X",
		"_X X  * * XX X",
		"_X  XXX  XX  X",
		"_X    XX XX XX",
		"_X  * X  *  X",
		"_XXX* *   XXX",
		"___X  XXXXX",
		"___XXXX"
	},
	{
		"______________XXX",
		"_____________XX.XXX",
		"_____________X....X",
		"_XXXXXXXXXXXXX....X",
		"XX   XX     XX....XXXXX",
		"X  **XX  * @XX....    X",
		"X      ** *X  ....X   X",
		"X  * XX ** X X....X  XX",
		"X  * XX *  X XX XXX  X",
		"XX XXXXX XXX         X",
		"XX   *  * XXXXX XXX  X",
		"X *XXX  X XXXXX X_XXXX",
		"X   *   X       X",
		"X  * X* * *XXX  X",
		"X ***X *   X_XXXX",
		"X    X  ** X",
		"XXXXXX   XXX",
		"_____XXXXX"
	},
	{
		"______XXXX",
		"XXXXXXX @X",
		"X     *  X",
		"X   *XX *X",
		"XX*X...X X",
		"_X *...  X",
		"_X X. .X XX",
		"_X   X X* X",
		"_X*  *    X",
		"_X  XXXXXXX",
		"_XXXX"
	},
	{
		"___________XXXXX",
		"__________XX   XX",
		"_________XX     X",
		"________XX  **  X",
		"_______XX **  * X",
		"_______X *    * X",
		"XXXX___X   ** XXXXX",
		"X  XXXXXXXX XX    X",
		"X..           ***@X",
		"X.X XXXXXXX XX   XX",
		"X.X XXXXXXX. X* *XXX",
		"X........... X   * X",
		"XXXXXXXXXXXXXX  *  X",
		"_____________XX  XXX",
		"______________XXXX"
	},
	{
		"_XXXXXXXX",
		"_X@XX   XXXX",
		"_X *   *   X",
		"_X  * * ***X",
		"_X **X X   X",
		"XX*    *   X",
		"X  *  *****XX",
		"X *XXXX X   X",
		"X  *....X   X",
		"X XX....X** X",
		"X XX....   XX",
		"X   ....X  X",
		"XX X....X**X",
		"_X X....X  X",
		"_X         X",
		"_XXXX XX*XXX",
		"____X    X",
		"____XXXXXX"
	},
	{
		"____XXXXXXXXXXXX",
		"____X          XX",
		"____X  X X** *  X",
		"____X* X*X  XX @X",
		"___XX XX X * X XX",
		"___X   * X*  X X",
		"___X   X *   X X",
		"___XX * *   XX X",
		"___X  X  XX  * X",
		"___X    XX **X X",
		"XXXXXX**   X   X",
		"X....X  XXXXXXXX",
		"X.X... XX",
		"X....   X",
		"X....   X",
		"XXXXXXXXX"
	},
	{
		"______XXXXXX",
		"___XXXXX   X",
		"___X   X X XXXXX",
		"___X * X  *    XXXXXX",
		"__XX*  XXX XX       X",
		"XXX  ** * * X  XX   XXXXX",
		"X       *   XXXXXX XX   X",
		"X  XXXXXXXX X@   X X  X X",
		"XX XXX      XXXX X*X X  X",
		"_X XXX XXXX XX.. X   * XX",
		"_X  *  *  X*XX.. X*XX  XX",
		"_X  X X X     ..XX XX * X",
		"_XXXX   X XX X..X    *  X",
		"____XXXXX    X..X X X  XX",
		"________XXXXXX..X   X XX",
		"_____________X..XXXXX  X",
		"_____________X..       X",
		"_____________XX  XXX  XX",
		"______________XXXXXXXXX"
	},
	{
		"________XXXXXXX",
		"____XXXXX  X  XXXX",
		"____X   X   *    X",
		"_XXXX X** XX XX  X",
		"XX      X X  XX XXX",
		"X  XXX *X*  *  *  X",
		"X...    X XX  X   X",
		"X...X    @ X XXX XX",
		"X...X  XXX  *  *  X",
		"XXXXXXXX_XX   X   X",
		"__________XXXXXXXXX"
	},
	{
		"____XXXXXXXXX__XXXX",
		"____X   XX  XXXX  X",
		"____X   *   X  *  X",
		"____X  X XX X     XXXX",
		"____XX *   * **X X   X",
		"____XXXX  X  X * *   X",
		"XXXXX  XXXX    XXX...X",
		"X   X* X  X XXXX.....X",
		"X      X  X X XX.....X",
		"XXXXXX X  X*   XXX...X",
		"___X   XX X *X   X...X",
		"__XX       *  *X XXXXX",
		"_XX ***XX  X *   X",
		"_X   X  X XXX  XXX",
		"_X   *  X* @XXXX",
		"_XXXXX  X   X",
		"_____XXXXXXXX"
	},
	{
		"_XXXXX",
		"_X   X",
		"_X X XXXXXX",
		"_X      *@XXXXXX",
		"_X * XX* XXX   X",
		"_X XXXX *    * X",
		"_X XXXXX X  X* XXXX",
		"XX  XXXX XX*      X",
		"X  *X  *  X XX XX X",
		"X         X X...X X",
		"XXXXXX  XXX  ...  X",
		"_____XXXX_X X...X X",
		"__________X XXX X X",
		"__________X       X",
		"__________XXXXXXXXX"
	},
	{
		"_______XXXX",
		"_______X  XX",
		"_______X   XX",
		"_______X ** XX",
		"_____XXX*  * XX",
		"__XXXX    *   X",
		"XXX  X XXXXX  X",
		"X    X X....* X",
		"X X   * ....X X",
		"X  * X X.&..X X",
		"XXX  XXXX XXX X",
		"__XXXX @*  XX*XX",
		"_____XXX *     X",
		"_______X  XX   X",
		"_______XXXXXXXXX"
	},
	{
		"______XXXXXXXXXXXX",
		"_____XX..    X   X",
		"____XX..& *    * X",
		"___XX..&.X X X* XX",
		"___X..&.X X X *  X",
		"XXXX...X  X    X X",
		"X  XX X          X",
		"X @* * XXX  X X XX",
		"X *   *   X X   X",
		"XXX**   X X X X X",
		"__X   *   X X XXXXX",
		"__X *X XXXXX      X",
		"__X*   X___X   X  X",
		"__X  XXX___XX     X",
		"__X  X______X    XX",
		"__XXXX______XXXXXX"
	},
	{
		"_____XXXXXXXXXXXXX",
		"_____X    XXX    X",
		"_____X     * *  XXXX",
		"___XXXX X   * *    X",
		"__XX *  X*XXXX * * X",
		"XXX   X X   XXX  * X",
		"X *  *  X  *  X XXXX",
		"X XX*XXXX X*X  *  XXX",
		"X XX  XXX X X X  *  X",
		"X    @*   *   X * X X",
		"XXXXX  X  XX  X *X  X",
		"__X... XXXXX*  X  X X",
		"__X.......X ** X* X X",
		"__X.......X         X",
		"__X.......XXXXXXX  XX",
		"__XXXXXXXXX_____XXXX"
	},
	{
		"XXXXX_XXXX",
		"X...X_X  XXXX",
		"X...XXX  *  X",
		"X....XX *  *XXX",
		"XX....XX   *  X",
		"XXX... XX * * X",
		"X XX    X  *  X",
		"X  XX X XXX XXXX",
		"X * X X*  *    X",
		"X  * @ *    *  X",
		"X   X * ** * XXX",
		"X  XXXXXX  XXX",
		"X XX____XXXX",
		"XXX"
	},
	{
		"_XXXX",
		"XX  XXXXX",
		"X       X_XXXXX",
		"X *XXX  XXX   X",
		"X..X  *X X  X X",
		"X..X      **X XXX",
		"X.&X X  X* *    XXXXX",
		"X..X  XX     XX*X   X",
		"X.&*  * X XX  *     X",
		"X..XX  *   X   XXXXXX",
		"X.&XX*XX   XXXXX",
		"X..  * XXXXX",
		"X  X @ X",
		"XXXXXXXX"
	},
	{
		"___XXXXXXXXXX",
		"___X  XXX   X",
		"___X *   *  X",
		"___X  XXXX*XX",
		"___XX X  X  X",
		"__XX  X.&   X",
		"__X  XX..X  X",
		"__X @ X.&X XX",
		"__X X*X..X* X",
		"__X * X..X  X",
		"__X X X&&X  X",
		"__X * X..X*XX",
		"__X    .&X  X",
		"_XXX  X  X  X",
		"XX    XXXX  X",
		"X  XXXXXXX*XX",
		"X *      *  X",
		"X  XX   X   X",
		"XXXXXXXXXXXXX"
	},
	{
		"_XXXXXXXXXXXXXXXXXXXXX",
		"_X   XX  X   X   X   X",
		"_X *     *   *   *   XX",
		"XXXXX X  X   XXX XX*XXX",
		"X   X XX*XXXXXX   X   X",
		"X *   X ......X   X * X",
		"XX X  X ......XXXXX   X",
		"XX XXXXXXXXX..X   X XXX",
		"X          X..X *   X",
		"X XX XXX XXX..XX X  XXX",
		"X X   X   XX..XX XXX  X",
		"X   @      *..X       X",
		"X X   X   XX  X   XX  X",
		"XXXXX XXXXXXXXXXXXXX XX",
		"X          X   X    * X",
		"X *  X * * *   X X    X",
		"X X*XX *X  XX XX    X X",
		"X  * ** XXXX *  * X X X",
		"X          X   X      X",
		"XXXXXXXXXXXXXXXXXXXXXXX"
	},
	{
		"_XXXXXXXXXXXXXXXXXXXXX",
		"XX                   X",
		"X    * X      XX X   X",
		"X  XXXXXX XXX  X*XX XX",
		"XX*X   XX*X....   X X",
		"X  X    * X....XX X X",
		"X * X X X X....XX   X",
		"X * X**   X....XX*X X",
		"X X *@*XX*X....XX   X",
		"X   ***   X....X    X",
		"X  *X   X XXXXXX *XXX",
		"XX  X XXX**  *   * X",
		"XX     X *  * XX   X",
		"_XXXXX   X   XXXXXXX",
		"_____XXXXXXXXX"
	},
	{
		"XXXXXXXXXX",
		"X        XXXX",
		"X XXXXXX X  XX",
		"X X * * *  * X",
		"X       X*   X",
		"XXX*  **X  XXX",
		"__X  XX X *XX",
		"__XX*X   * @X",
		"___X  * * XXX",
		"___X X   *  X",
		"___X XX   X X",
		"__XX  XXXXX X",
		"__X         X",
		"__X.......XXX",
		"__X.......X",
		"__XXXXXXXXX"
	},
	{
		"_________XXXX",
		"_XXXXXXXXX  XX",
		"XX  *      * XXXXX",
		"X   XX XX   XX...X",
		"X X** * **X*XX...X",
		"X X    @  X   ...X",
		"X  *X XXX**   ...X",
		"X *  **  * XX....X",
		"XXX*       XXXXXXX",
		"__X  XXXXXXX",
		"__XXXX"
	},
	{
		"______________XXXXXX",
		"__________XXXXX    X",
		"__________X  XX X  XXXXX",
		"__________X   &.X..X   X",
		"_XXXXX_XXXX *X.X...    X",
		"_X   XXX  XX X&....XX XX",
		"_X *      XX X..X..XX X",
		"XXXXXX X   X X&.XXXXX X",
		"X   X *X*X X X..XXXXX X",
		"X *  *     X X&.    X X",
		"XX XX  * XXX X  XX  X X",
		"_X  *  * XXX XXXXX XX X",
		"_XXX*XXX*XXX  XXXX XX X",
		"XXXX X         XXX  X X",
		"X  * X  *XXXX  XXX**X@XXXXX",
		"X      * X_X  XXXX  X*X   X",
		"XXXX X  *X_X              X",
		"___X  *  X_XX  XX  XXXXXXXX",
		"___XX  XXX__XXXXXXXX",
		"____XXXX"
	},
	{
		"_________XXXX",
		"_________X  X",
		"_________X  XXXXXXXX",
		"___XXXXXXX  X      X",
		"___X   X X X X X   XX",
		"___X *     *  XX  * X",
		"__XXX *X X  X X     XXXXXXXXX",
		"__X  *  X  *X X ** X   X X  X",
		"_XX X   X     XXX    * X X  X",
		"_X  X*   X XXX  X  X **X X  X",
		"_X    *XX *  X   XX *  X X XX",
		"XXXX* * X    XX  X   *    ..X",
		"X  X    XXX X * * XXX  XXX.&X",
		"X     XX  ** @  *     XX....X",
		"X  XX  XX   *  X*X  XX....&.X",
		"XX X  *  X X *XX  XX....&.XXX",
		"XX XX  *  X * X  X....&.XXX",
		"X    * XXXX   X ....&.XXX",
		"X   X  X__X  X  ..&.XXX",
		"XXXXXXXX__XXXXXXXXXXX"
	},
	{
		"________XXXXX",
		"________X   XXXX",
		"________X *    XXXX__XXXX",
		"________X   X *X  XXXX  X",
		"XXXXXXXXXXX X   *   X   X",
		"X..     X *  XXXX X  X  X",
		"X..*  X   *  X  * X * .XX",
		"X.&X X * * XX  XX    X.X",
		"X..X* @ X   XX    ** X.X",
		"X..X * *  * * XX   XX .X",
		"X.&** X XX   * X*X * X.X",
		"X..X      XX   X     X.X",
		"X..XXXXXXX  XXX XXXXXX.XX",
		"X **                  &.XX",
		"X  XXXXXXXXXXXXXXXXXX  ..X",
		"XXXX________________XXXXXX"
	}
}
